version: "3.8"

services:
  web:
    build: .
    container_name: biblioteca_app
    ports:
      - "81:8000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-clave-super-secreta-cambiar-en-produccion}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - db_data:/app/instance
      - log_data:/app/logs
    restart: unless-stopped
    # ESTO ES LO NUEVO: Conecta el contenedor a la red de Coolify
    networks:
      - coolify

# DEFINIR LA RED EXTERNA
networks:
  coolify:
    external: true