version: "3.8"

services:
  web:
    build: .
    container_name: biblioteca_app
    ports:
      - "81:8000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-clave-super-secreta-cambiar-en-produccion}
      - DATABASE_URL=postgresql://admin:12345678Ab@postgres_db:5435/master_db
    depends_on:
      - postgres_db
    volumes:
      - db_data:/app/instance
      - log_data:/app/logs
    restart: unless-stopped
    networks:
      - coolify

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678Ab
      - POSTGRES_DB=master_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - coolify

volumes:
  db_data:
  log_data:
  postgres_data:

networks:
  coolify:
    external: true