"""Agregar tabla multas

Revision ID: 1b725bfce75d
Revises: 
Create Date: 2026-05-19 15:34:01.165266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b725bfce75d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multas',
    sa.Column('id_multa', sa.Integer(), nullable=False),
    sa.Column('tipo_recurso', sa.String(length=20), nullable=False),
    sa.Column('id_prestamo_equipo', sa.Integer(), nullable=True),
    sa.Column('id_prestamo_libro', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('dias_retraso', sa.Integer(), nullable=False),
    sa.Column('dias_suspension', sa.Integer(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_inicio_suspension', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin_suspension', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('id_administrador_resolucion', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_administrador_resolucion'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_prestamo_equipo'], ['prestamos.id_prestamo'], ),
    sa.ForeignKeyConstraint(['id_prestamo_libro'], ['prestamos_libros.id_prestamo_libro'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_multa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multas')
    # ### end Alembic commands ###

